### ISSUE TITLE
VSCPresetEditor-v0.0.5 can't overwrite files

### ISSUE THREAD

**Issue by Deliphin** [Foghrye4/VerticalSpawnControl#1]
I first downloaded the example template provided here:
http://www.mediafire.com/file/2lqsi0255o2j3ip/vertical_spawn_control.json

I made some edits, and saved over that file.

Upon opening that file, my edits were gone, the save never occurred.

I was trying to make the same preset as I have in #2.

**Comment by Foghrye4** [comment]
Wasn't able to reproduce. Probably a Windows thing. Check if files has a "read only" attribute.

**Comment by Deliphin** [comment]
..Okay, not sure how or why, but you were right, the file DOES have read-only enabled.
